
package principal;
import paneles.CambiaPanel;
import paneles.pnlProveedores;
import paneles.pnlProductos;
import paneles.pnlEmpleados;
import paneles.pnlUsuarios;
/**
 *
 * @author AndyMontiel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        btnCerrarSesion = new rsbuttom.RSButtonMetro();
        pnlSliding = new javax.swing.JPanel();
        pnlMenuSliding = new javax.swing.JPanel();
        btnVentas = new rsbuttom.RSButtonMetro();
        btnCompras = new rsbuttom.RSButtonMetro();
        btnInventario = new rsbuttom.RSButtonMetro();
        btnProductos = new rsbuttom.RSButtonMetro();
        btnProveedores = new rsbuttom.RSButtonMetro();
        btnClientes = new rsbuttom.RSButtonMetro();
        btnEmpleados = new rsbuttom.RSButtonMetro();
        btnUsuarios = new rsbuttom.RSButtonMetro();
        pnlContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido al sistema ERP");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1536, 899));
        setName("FormularioERP"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1550, 900));
        setResizable(false);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTop.setBackground(new java.awt.Color(0, 200, 255));
        pnlTop.setForeground(new java.awt.Color(0, 200, 255));
        pnlTop.setToolTipText("");

        btnCerrarSesion.setBackground(new java.awt.Color(0, 200, 255));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnCerrarSesion.setColorHover(new java.awt.Color(0, 200, 255));
        btnCerrarSesion.setColorNormal(new java.awt.Color(0, 200, 255));
        btnCerrarSesion.setColorPressed(new java.awt.Color(0, 200, 255));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(1452, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlPrincipal.add(pnlTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 70));

        pnlSliding.setBackground(new java.awt.Color(79, 79, 79));
        pnlSliding.setForeground(new java.awt.Color(79, 79, 79));

        pnlMenuSliding.setBackground(new java.awt.Color(79, 79, 79));

        btnVentas.setBackground(new java.awt.Color(79, 79, 79));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/venta.png"))); // NOI18N
        btnVentas.setToolTipText("Generar Venta.");
        btnVentas.setColorHover(new java.awt.Color(79, 79, 79));
        btnVentas.setColorNormal(new java.awt.Color(79, 79, 79));
        btnVentas.setColorPressed(new java.awt.Color(79, 79, 79));
        btnVentas.setPreferredSize(new java.awt.Dimension(80, 80));

        btnCompras.setBackground(new java.awt.Color(79, 79, 79));
        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compra.png"))); // NOI18N
        btnCompras.setToolTipText("Realizar Compra.");
        btnCompras.setColorHover(new java.awt.Color(79, 79, 79));
        btnCompras.setColorNormal(new java.awt.Color(79, 79, 79));
        btnCompras.setColorPressed(new java.awt.Color(79, 79, 79));
        btnCompras.setPreferredSize(new java.awt.Dimension(80, 80));

        btnInventario.setBackground(new java.awt.Color(79, 79, 79));
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inventario.png"))); // NOI18N
        btnInventario.setToolTipText("Inventario.");
        btnInventario.setColorHover(new java.awt.Color(79, 79, 79));
        btnInventario.setColorNormal(new java.awt.Color(79, 79, 79));
        btnInventario.setColorPressed(new java.awt.Color(79, 79, 79));
        btnInventario.setPreferredSize(new java.awt.Dimension(80, 80));

        btnProductos.setBackground(new java.awt.Color(79, 79, 79));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/productos.png"))); // NOI18N
        btnProductos.setToolTipText("Productos.");
        btnProductos.setColorHover(new java.awt.Color(79, 79, 79));
        btnProductos.setColorNormal(new java.awt.Color(79, 79, 79));
        btnProductos.setColorPressed(new java.awt.Color(79, 79, 79));
        btnProductos.setPreferredSize(new java.awt.Dimension(80, 80));
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnProveedores.setBackground(new java.awt.Color(79, 79, 79));
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proveedores.png"))); // NOI18N
        btnProveedores.setToolTipText("Proveedores.");
        btnProveedores.setColorHover(new java.awt.Color(79, 79, 79));
        btnProveedores.setColorNormal(new java.awt.Color(79, 79, 79));
        btnProveedores.setColorPressed(new java.awt.Color(79, 79, 79));
        btnProveedores.setPreferredSize(new java.awt.Dimension(80, 80));
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(79, 79, 79));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        btnClientes.setToolTipText("Clientes.");
        btnClientes.setColorHover(new java.awt.Color(79, 79, 79));
        btnClientes.setColorNormal(new java.awt.Color(79, 79, 79));
        btnClientes.setColorPressed(new java.awt.Color(79, 79, 79));
        btnClientes.setPreferredSize(new java.awt.Dimension(80, 80));

        btnEmpleados.setBackground(new java.awt.Color(79, 79, 79));
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empleado.png"))); // NOI18N
        btnEmpleados.setToolTipText("Empleados.");
        btnEmpleados.setColorHover(new java.awt.Color(79, 79, 79));
        btnEmpleados.setColorNormal(new java.awt.Color(79, 79, 79));
        btnEmpleados.setColorPressed(new java.awt.Color(79, 79, 79));
        btnEmpleados.setPreferredSize(new java.awt.Dimension(80, 80));
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });

        btnUsuarios.setBackground(new java.awt.Color(79, 79, 79));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        btnUsuarios.setToolTipText("Usuarios");
        btnUsuarios.setColorHover(new java.awt.Color(79, 79, 79));
        btnUsuarios.setColorNormal(new java.awt.Color(79, 79, 79));
        btnUsuarios.setColorPressed(new java.awt.Color(79, 79, 79));
        btnUsuarios.setPreferredSize(new java.awt.Dimension(80, 80));
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuSlidingLayout = new javax.swing.GroupLayout(pnlMenuSliding);
        pnlMenuSliding.setLayout(pnlMenuSlidingLayout);
        pnlMenuSlidingLayout.setHorizontalGroup(
            pnlMenuSlidingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuSlidingLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlMenuSlidingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlMenuSlidingLayout.setVerticalGroup(
            pnlMenuSlidingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuSlidingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSlidingLayout = new javax.swing.GroupLayout(pnlSliding);
        pnlSliding.setLayout(pnlSlidingLayout);
        pnlSlidingLayout.setHorizontalGroup(
            pnlSlidingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSlidingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMenuSliding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlSlidingLayout.setVerticalGroup(
            pnlSlidingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSlidingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMenuSliding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlPrincipal.add(pnlSliding, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 820));

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenedor.setLayout(new javax.swing.BoxLayout(pnlContenedor, javax.swing.BoxLayout.LINE_AXIS));
        pnlPrincipal.add(pnlContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 1360, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        new CambiaPanel(pnlContenedor, new pnlProveedores());
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        new CambiaPanel(pnlContenedor, new pnlProductos());
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        new CambiaPanel(pnlContenedor, new pnlEmpleados());
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        new CambiaPanel(pnlContenedor, new pnlUsuarios());
    }//GEN-LAST:event_btnUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnCerrarSesion;
    private rsbuttom.RSButtonMetro btnClientes;
    private rsbuttom.RSButtonMetro btnCompras;
    private rsbuttom.RSButtonMetro btnEmpleados;
    private rsbuttom.RSButtonMetro btnInventario;
    private rsbuttom.RSButtonMetro btnProductos;
    private rsbuttom.RSButtonMetro btnProveedores;
    private rsbuttom.RSButtonMetro btnUsuarios;
    private rsbuttom.RSButtonMetro btnVentas;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlMenuSliding;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSliding;
    private javax.swing.JPanel pnlTop;
    // End of variables declaration//GEN-END:variables
}
